### ISSUE TITLE
v0.6.1 not available when running fastlane update_plugins

### ISSUE THREAD

**Issue by itsthejb** [EmergeTools/fastlane-plugin-emerge#12]
Hi,

I notice that 0.6.1 has been available for some time. However when running `fastlane update_plugins` this version isn't available. Also if attempting to manually update the version, it fails:

```
❯ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Could not find fastlane-plugin-emerge-0.6.1 in any of the sources
```

Perhaps some issue here? Thanks

**Comment by noahsmartin** [comment]
Just pushed the latest release to ruby gems (0.6.2) so you should be able to use that one now. Thanks for reporting!
